.\" Manpage for timemachine.
.\" Contact dtrajkovic@solution-soft.com to correct errors or typos.
.TH man 8 "11 November 2020" "1.1" "time machine man page"
.SH SYNOPSIS
To create a virtual clock /opt/ssstm/bin/tmuser -a -G -y 5  # this adds a virtual clock for the whole pod that is 5 years in the future
.SH DESCRIPTION
Time Machine lets you create virtual clocks for time shift testing. The software is installed in the container at /opt/ssstm. 

 
.SH BUGS
No known bugs.
.SH AUTHOR
Ken Zhao (kzhao@solution-soft.com)
